data_class: 'PUREYULIAO'
model_class: GPT2Chinese
data_class_module: "gpt2_generator.data"
model_class_module: "gpt2_generator.lit_models"

data:
  gpus: (gpus, 0)
  n_ctx: 1024
  stride: 678
  tokenizer_path: 'gpt2_generator/models/final_model/gpt2/vocab.txt'
  batch_size: 4
  num_workers: 8
  raw: True
  raw_dir: 'gpt2_generator/data/demo/raw'
  train_dir: 'gpt2_generator/data/demo/train'


litmodel:
  load_checkpoint: 'None'
  optimizer: 'Adam'
  lr: 1e-3
  one_cycle_max_lr: 1e-3
  one_cycle_total_steps: 100
  loss: cross_entropy
  stop_early: False
  final_path: "gpt2_generator/models/final_model/gpt2"

chkpt:
  every_n_epochs: 2

model:

