trainer:
  stop_early: False
  max_epochs: 200
  devices: 1
  strategy: 'deepspeed_stage_3'
  accelerator: 'gpu'
  fp: 16
  gas: 8
  debug_mode: False

data:
  data_dir: '/root/autodl-tmp/dataset'
  #data_dir: 'files/dataset/'
  raw_file_type: 'json'
  max_seq_length: 724
  train_batchsize: 4
  valid_batchsize: 2
  do_eval_only: False
  n_ctx: 1024
  stride: 678
  num_workers: 2
  #hf_data: 'IDEA-CCNL/Ziya-Finetune-Small'
  hf_data: False

model:
  #pretrained_file: "IDEA-CCNL/Wenzhong-GPT2-110M" 
  #base_model: "openlmlab/open-chinese-llama-7b-patch" 
  base_model: "IDEA-CCNL/Wenzhong2.0-GPT2-3.5B-chinese" 
  train_batchsize: 2
  cache_dir: '/root/autodl-tmp/wenzhong'
  #cache_dir: '/Volumes/T7/FileBackup/lora_model/llama_opemlmlab'
  load_checkpoint: False
  ckpt_dir: '/root/autodl-tmp/ckpt/20230707_llam_whole/last.ckpt'
  weight_decay: 0.00001
  learning_rate: 0.0003
  warmup: 0.01
lora:
  lora_r: 8
  lora_alpha: 16
  lora_dropout: 0.05
  lora_target_modules: [
    "c_attn",
]

ckpt:
  monitor: 'train_loss'
  save_top_k: 1
  mode: 'min'
  every_n_train_steps: 100
  save_weights_only: True
  dirpath: '/root/autodl-tmp/ckpt'
  save_last: True
  file_name: 'Default'

test:
  ckpt_path: '/root/autodl-tmp/ckpt/test_0.01.pt'
