
trainer:
  stop_early: False
  chkpt_every_n_epochs: 10
  max_epochs: 10
  devices: 1
  strategy: 'auto'
  accelerator: 'cpu'

data:
  data_class: 'TESTYULIAO'
  data_class_module: "training.data_loader"
  n_ctx: 1024
  stride: 678
  batch_size: 1
  num_workers: 0
  raw: True
  raw_dir: 'files/dataset/demo/raw'
  train_dir: 'files/dataset/demo/train'

tokenizer:
  tokenizer_path: 'files/tokenizer/vocab.txt'
kg:
  model_name: 'bert-base-chinese'
  pretrained_file: 'files/kg_bert_final_model'
  load_checkpoint: 'None'
  optimizer: 'Adam'
  lr: 0.0001
  loss: cross_entropy
  num_lables: 4

gpt2:
  pretrained_file: "files/gpt2_gpt2_final_model" 
  load_checkpoint: 'None'
  loss: cross_entropy
  optimizer: 'Adam'
  lr: 0.001

litmodel:
  one_cycle_max_lr: 1e-3
  one_cycle_total_steps: 100
  final_path: 


