trainer:
  stop_early: False
  chkpt_every_n_epochs: 10
  max_epochs: 20
  devices: 1
  strategy: 'ddp'
  accelerator: 'gpu'

data:
  data_class: 'KGYULIAO'
  data_class_module: "training.data_loader"
  n_ctx: 1024
  stride: 678
  batch_size: 1
  num_workers: 0
  raw: True
  raw_dir: 'files/dataset/demo/raw'
  train_dir: 'files/dataset/demo/train'

tokenizer:
  tokenizer_path: 'files/tokenizer/vocab.txt'
  #tokenizer_path: 'bert-base-chinese'
kg:
  pretrained_file: 'files/kg_bert_final_model'
  num_labels: 4
  load_checkpoint: 'None'
  checkpoint_path: 'files/kg_chkpt/****.ckpt'
  optimizer: 'Adam'
  lr: 0.0001
  loss: cross_entropy

gpt2:
  pretrained_file: "files/gpt2_gpt2_final_model" 
  load_checkpoint: 'None'
  loss: cross_entropy
  optimizer: 'Adam'
  lr: 0.001