trainer:
  stop_early: False
  max_epochs: 200
  devices: 4
  strategy: 'deepspeed_stage_3'
  accelerator: 'gpu'

data:
  data_class: 'WenzhongQADataModel'
  data_class_module: "training.data_loader"
  data_path: 'files/dataset/wyl'
  max_seq_length: 1024
  train_batchsize: 8
  valid_batchsize: 2
  do_eval_only: False
  n_ctx: 1024
  stride: 678
  num_workers: 16
  data_type_name: 'JSON'

tokenizer:
  tokenizer_path: 'IDEA-CCNL/Wenzhong-GPT2-110M'
  #tokenizer_path: 'IDEA-CCNL/Wenzhong2.0-GPT2-3.5B-chinese'

gpt2:
  pretrained_file: "IDEA-CCNL/Wenzhong-GPT2-110M" 
  #pretrained_file: "IDEA-CCNL/Wenzhong2.0-GPT2-3.5B-chinese" 
  load_checkpoint: False
  lr: 0.0001
  weight_decay: 0.1
  learning_rate: 0.0001
  warmup: 0.01

ckpt:
  monitor: 'train_loss'
  save_top_k: 3
  mode: 'min'
  every_n_train_steps: 100
  save_weights_only: True
  dirpath: '/autodl_tmp/ckpt'
  save_last: True
  file_name: 'Default'

test:
  ckpt_path: '/Users/sunlin/Documents/workdir/situationAwareness_0528/kg_trainer/files/rename.ckpt/final.ckpt'
